rm #!/bin/bash
rm ./lib/libssl.so.0.9.8
rm ./lib/libssl.pc
rm ./lib/libcrypto.a
rm ./lib/libcrypto.so.0.9.8
rm ./lib/libssl.a
rm ./lib/libcrypto.pc
rm ./lib/libcrypto.so
rm ./lib/libssl.so
rm ./arm-1176-linux-gnueabi/sysroot/lib
rm ./arm-1176-linux-gnueabi/sysroot/lib/libssl.so.0.9.8
rm ./arm-1176-linux-gnueabi/sysroot/lib/libssl.pc
rm ./arm-1176-linux-gnueabi/sysroot/lib/libcrypto.a
rm ./arm-1176-linux-gnueabi/sysroot/lib/libcrypto.so.0.9.8
rm ./arm-1176-linux-gnueabi/sysroot/lib/libssl.a
rm ./arm-1176-linux-gnueabi/sysroot/lib/libcrypto.pc
rm ./arm-1176-linux-gnueabi/sysroot/lib/libcrypto.so
rm ./arm-1176-linux-gnueabi/sysroot/lib/libssl.so
rm ./usr/lib/libssl.so.0.9.8
rm ./usr/lib/libssl.pc
rm ./usr/lib/libcrypto.a
rm ./usr/lib/libcrypto.so.0.9.8
rm ./usr/lib/libssl.a
rm ./usr/lib/libcrypto.pc
rm ./usr/lib/libcrypto.so
rm ./usr/lib/libssl.so
